import { readFile, writeFile, mkdir, copyFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import postcss from 'postcss';
import { compileTokens, flatten, loadTokens, resolve } from './tokens.mjs';

const write = async (path, content) => {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content);
};
const tokens = await loadTokens();
await mkdir('apps/storybook/public/licenses', { recursive: true });
await copyFile(
  'node_modules/@fontsource/inter/LICENSE',
  'apps/storybook/public/licenses/Inter.txt',
);
await copyFile('packages/ui/SHADCN-LICENSE', 'apps/storybook/public/licenses/shadcn-ui.txt');
for (const name of ['brand', 'tokens', 'ui']) {
  await copyFile('LICENSE', 'packages/' + name + '/LICENSE');
}
const aliases = JSON.parse(await readFile('packages/tokens/src/legacy-aliases.json', 'utf8'));
const overrides = flatten(
  JSON.parse(await readFile('packages/tokens/src/themes/dark.tokens.json', 'utf8')),
);
for (const [name, token] of Object.entries(overrides)) {
  if (!tokens[name] || token.$type !== tokens[name].$type)
    throw new Error('Invalid theme override: ' + name);
}
const darkTokens = { ...tokens, ...overrides };
const tokenCSS =
  compileTokens(tokens, aliases, ':root, [data-theme="light"]') +
  compileTokens(
    darkTokens,
    aliases,
    '[data-theme="dark"]',
    '[data-theme="dark"].axion, [data-theme="dark"] .axion',
  );
await write(
  'packages/tokens/dist/dark.tokens.json',
  JSON.stringify(
    Object.fromEntries(
      Object.entries(darkTokens).map(([name, token]) => [
        name,
        { ...token, $value: resolve(darkTokens, name) },
      ]),
    ),
    null,
    2,
  ) + '\n',
);
await write('packages/tokens/dist/tokens.css', '/* Generated by npm run build. */\n' + tokenCSS);
await write(
  'packages/tokens/dist/tokens.json',
  JSON.stringify(
    Object.fromEntries(
      Object.entries(tokens).map(([name, token]) => [
        name,
        { ...token, $value: resolve(tokens, name) },
      ]),
    ),
    null,
    2,
  ) + '\n',
);

const files = JSON.parse(await readFile('packages/ui/sources.json', 'utf8'));
files.push('packages/ui/src/foundations/accessibility.css');
const library = [];
const catalog = [];
for (const file of files) {
  const root = postcss.parse(await readFile(file, 'utf8'), { from: file });
  root.walkRules((rule) => {
    if (rule.parent.type === 'atrule' && rule.parent.name.endsWith('keyframes')) return;
    rule.selectors = rule.selectors.map((selector) =>
      ['body', 'html', '.axion'].includes(selector) ? '.axion' : ':where(.axion) ' + selector,
    );
  });
  (file.startsWith('docs/') ? catalog : library).push('/* ' + file + ' */\n' + root.toString());
}
const bundled =
  '/* Generated by npm run build. Edit packages/, not this file. */\n' +
  tokenCSS +
  '\n' +
  library.join('\n');
await write('packages/ui/dist/axion.css', bundled);
await write('styles.css', bundled + '\n' + catalog.join('\n'));
await mkdir('docs/site/vendor', { recursive: true });
await copyFile('node_modules/lucide/dist/umd/lucide.js', 'docs/site/vendor/lucide.js');
await copyFile('node_modules/lucide/LICENSE', 'docs/site/vendor/LUCIDE-LICENSE');
console.log(
  'Built ' + Object.keys(tokens).length + ' tokens and ' + files.length + ' style modules.',
);

const registry = JSON.parse(await readFile('registry.json', 'utf8'));
const template = await readFile('docs/site/example.template.html', 'utf8');
const escape = (value) =>
  value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
for (const resource of registry.resources) {
  const markup = await readFile(resource.source, 'utf8');
  await write(
    resource.example,
    template
      .replaceAll('{{name}}', escape(resource.name))
      .replace('{{markup}}', markup)
      .replace('{{documentation}}', resource.documentation),
  );
}
const resourceTemplate = await readFile('docs/site/resources.template.html', 'utf8');
const links = registry.resources
  .map(
    (resource) =>
      '<a href="' +
      resource.example +
      '"><strong>' +
      escape(resource.name) +
      '</strong><small>' +
      escape(resource.summary) +
      '</small></a>',
  )
  .join('\n');
await write('resources.html', resourceTemplate.replace('{{resources}}', links));
